### ISSUE TITLE
Distribute Robot checks with CheckMK Agent bakery

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#11]

**Comment by simonmeggle** [comment]
WIP in branch [bakery](https://github.com/simonmeggle/robotmk/tree/bakery)

**Comment by simonmeggle** [comment]
Proposal for Robot arguments which should be supported in the bakery rule and the agent plugin: 

Must-be: 
* `--name`: Set the name of the top level suite. Overrides auto naming from top level dir or robot file. 
* `--suite`: Select suites by name pattern
* `--test`: Select tests by name pattern
* `--include`: Select tests by tag pattern (exists already -> rename)
* `--exclude`: Exclude tests by tag pattern
* `--variablefile`: Load variables from file
* `--exitonfailure`: lets RF exit the whole suite if one test failed. (default is to execute all tests)
* `--argumentfile`: load additional args from this file. Could be useful if test execution should be manifested in the test repository.  

Optional: 
* `--critical/--noncritical` - pattern which tests are considered critical = can raise exceptions.

**Comment by simonmeggle** [comment]
#27 describes how the bakery could clone the test repository and bake the test files into the agent.

**Comment by mike1098** [comment]
This is done with agent bakery rule  "Deploy custom files with agent". Tested and works.

**Comment by simonmeggle** [comment]
What I wanted to remark is the possibility to include a version controlled test dir. For now it is ok to deliver the files with the existent bakery rule you mentioned.

**Comment by simonmeggle** [comment]
@guillaume-durville  : `argumentfile` is not a valid parameter when calling robot via python. I just have seen this. 
Options that do not take an argument (like `exitonfailure`) are given as boolean parameters: `exitonfailure=True`

**Comment by simonmeggle** [comment]
I have now written tests for the agent plugin and almost each possible robot argument (see above). 
For reference, you can inspect the `robotmk.yml` files  for each test/argument in https://github.com/simonmeggle/robotmk/tree/agentplugin/test/fixtures/plugin.

**Comment by simonmeggle** [comment]
I have now written tests for the agent plugin and almost each possible robot argument (see above). 
For reference, you can inspect the `robotmk.yml` files  for each test/argument in https://github.com/simonmeggle/robotmk/tree/agentplugin/test/fixtures/plugin.

**Comment by simonmeggle** [comment]
(already solved)
