### ISSUE TITLE
RobotMK Plugin "juggler" mode

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#12]
To get a first version as quick as possible, let's concentrate on the asynchronous execution of the robotmk plugin which then executes all suites in serial - each time it gets triggered. For this, a proper result caching time must be determined carefully. Chances are (and will, Mike :-) ) that tests run too long and test executions pass each other. This is hard to debug and error prone. 

Because of this fact, in a second step, this should be handled more intelligent. The plugin should be called on each agent execution (every minute) in "juggler" mode. The YML file provides the execution interval *per suite*. The plugin is responsible then to remember the last execution time of test X and if > interval, it should schedule a detached process of the plugin, which then acts in "wrapper" mode. In this case, the test output does not get to STDOUT but written to the agent spool dir. 
In juggler mode, the plugin also keeps track of the current number of running e2e tests and returns a proper error message if there is risk of overloading (very bad because tests running longer will produce WRONG perfdata and cause false alarms!). Further, it could respect the number of CPUs and free Memory to ensure that e2e test are always running under proper conditions.

**Comment by mike1098** [comment]
Sorry, thats exactly how the async mode of checkmk plugin works. No reason to reinvent what's already available and working.

**Comment by simonmeggle** [comment]
From what I know, the async mode lets you execute certain plugins in another (wider) interval that the agent check interval - that's OK, but nothing more.   

I try to explain which pain points I see.

- It requires to approach a caching interval which is slight higher than the maximum total runtime in the assumed worst case. As long as you did not find this magic number chances are that the last test suites are being bitten by the dog = not executed, because the caching time already was over and the next turn started. I know this from several Sakuli projects in former times where a series of suites got executed by a scheduled task/cron. It was a pain to find and set this **"intentional idle time"** - just to leave enough headroom for the case that some suites have longer runtimes as normal. 
- There is no support to run robot checks in parallel, and no support to control to run **as many  as are set to run as the machine's resources allow**. I see a demand for this when there is one fat testing machine provided to handle all tests simultaneously. (Already seen at customers)
- I do not see how we could be informed about **scheduling/timing problems** in another way than some checks are missing. The output of the plugin in juggler mode will itself report the success of the execution. I see a big advantage in the fact that the juggler still gets executed minutely, decides what should be started/spawned each as detached processes and can return _immediately_ with a lot of meta information: number of tests scheduled/executed, number of tests not executed to avoid overloading the machine, etc.  

Looking at this points, I personally do not see a reinvention of what is already there at all.

For now you still have convinced me to release RobotMK with asynchronous execution. :-)  
Let's see how the reactions from the community will be and if there are customers which are willing to support the juggler mode. (I won't develop anything which was not requested.)

**Comment by simonmeggle** [comment]
Related to #44 - the juggler mode will not be able to create processes which can interact with a user's desktop. 
Possible solution: write a small "RobotMK catcher" process which runs in the user context. 
Due to the fact that the juggler part is only running for a short mount of time, there is no continuous communication between juggler and catcher => use a file based message queue system like https://github.com/peter-wangxu/persist-queue.

**Comment by simonmeggle** [comment]
Will be solved in #59
