### ISSUE TITLE
In robotmk_wato_params_bakery.py "allow_empty" crashes in 2.0.0p5 

### ISSUE THREAD

**Issue by kleinski** [simonmeggle/robotmk#124]
![image](https://user-images.githubusercontent.com/3239736/120204277-eae09800-c228-11eb-8ee4-201714a5f498.png)

`Some GUI extensions could not be loaded. This may be caused by some incompatible extension packages.

Loading "/omd/sites/zwofuenf/local/share/check_mk/web/plugins/wato/robotmk_wato_params_bakery.py" failed: __init__() got an unexpected keyword argument 'allow_empty'`

No WATO elements regarding RobotMK are available. After deleting the corresponding "allow_empty" lines the error is vanished, but the agent plugin section of RobotMK is still not usable.

**Comment by simonmeggle** [comment]
@all-contributors please add @kleinski for bug
