### ISSUE TITLE
ModuleNotFoundError: No module named 'robot'

### ISSUE THREAD

**Issue by kleinski** [simonmeggle/robotmk#129]
According to the check_mk.log robotmk will be called via 
`2021-06-01 14:13:26.641 [srv 10044] perf:  In [856] milliseconds process 'C:\ProgramData\checkmk\agent\modules\python-3.8\.venv\Scripts\python.exe C:\ProgramData\checkmk\agent\plugins\robotmk-runner.py' pid:[3828] SUCCEDED - generated [0] bytes of data in [0] blocks`

As there has not been anything included in the agent's output regarding robotmk: 

![image](https://user-images.githubusercontent.com/3239736/120321847-11173e00-c2e4-11eb-8e1c-d6ac6cdeb5b0.png)

**Comment by simonmeggle** [comment]
I did not use another python interpreter than the system wide so far. 
Did you `pip install` the modules in this venv, too?

**Comment by kleinski** [comment]
> I did not use another python interpreter than the system wide so far.
> Did you `pip install` the modules in this venv, too?

Nope but CheckMK brings its own python runtime interpreter from version 2.0 afaik.

**Comment by simonmeggle** [comment]
That's beyond my scope :-) I always installed Python by hand. 
But perhaps an interesting approach to use the agent's interpreter.

**Comment by kleinski** [comment]
Yes, I am trying now to switch into that venv, but it's a bit tricky.

**Comment by kleinski** [comment]
But maybe the rule _Install Python runtime environment_ may help as well. Will check that out and report.

**Comment by kleinski** [comment]
The corresponding werk: https://checkmk.com/werk/10689

**Comment by kleinski** [comment]
If switched off like this, the system wide python interpreter is called: 
![image](https://user-images.githubusercontent.com/3239736/120325074-94865e80-c2e7-11eb-926a-f3d7c9ce786e.png)
`2021-06-01 14:40:54.952 [srv 8924] perf:  In [2653] milliseconds process 'python.exe "C:\ProgramData\checkmk\agent\plugins\robotmk.py"' pid:[4348] SUCCEDED - generated [389] bytes of data in [1] blocks`

**Comment by simonmeggle** [comment]
Interesting... 
Is there any way to manage the module set to that RF and its libraries can also be installed with the agent? 
The reason I am asking is that this approach could work well only if it replaces the manual agent configuration _completely_. If there are still manual tasks remaining, I don't see added value.

**Comment by simonmeggle** [comment]
Closing this issue; if you are getting the error message, try @kleinski's solution above. 
Will add a hint to the docs, see #132
