### ISSUE TITLE
NameError: name 'MKGeneralException' is not defined

### ISSUE THREAD

**Issue by a-lohmann** [simonmeggle/robotmk#138]
Hi Simon,

While trying out RobotMK on CheckMK version 2, I ran into the following error:

```
  File "/omd/sites/sitename/local/lib/python3/cmk/base/plugins/agent_based/robotmk.py", line 67, in parse_robotmk
    raise MKGeneralException(
NameError: name 'MKGeneralException' is not defined
```

The exception itself was my own mistake, but it does look like you forgot to import the exception library. Adding `from cmk.utils.exceptions import MKGeneralException` to `checks/v2/robotmk.py` seems to fix the issue. 

If you want I can raise a PR, but wanted to check with you first.

Kind regards

**Comment by simonmeggle** [comment]
Hi @a-lohmann ,
thanks for pointing this out. Sounds reasonable - please create a pull request. 
Thanks!
Simon

**Comment by simonmeggle** [comment]
@all-contributors please add @a-lohmann for bug

**Comment by a-lohmann** [comment]
Hi Simon,

Here's the PR: https://github.com/simonmeggle/robotmk/pull/140

Kind regards,
Antal

**Comment by simonmeggle** [comment]
Thanks, merged!
