### ISSUE TITLE
Agent Plugin robotmk-runner.py has CRLF Endings

### ISSUE THREAD

**Issue by NimVek** [simonmeggle/robotmk#146]
The packed robotmk-runny.py has CRLF Endings, wich it makes it broken in this form.

localhost:~ # ./robotmk-runner.py
/usr/bin/env: ‘python3\r’: No such file or directory

The robotmk.py is perfect.
I could not comprehend the whole package release process, so i unfortunately cannot help to find the right place to fix it.

Reproducible in package:
robotmk.v1.1.0-cmk2.mkp
robotmk.v1.1.1-beta-cmk2.mkp

**Comment by simonmeggle** [comment]
Thanks, I will release a new beta version today to fix that asap.

**Comment by simonmeggle** [comment]
@all-contributors please add @NimVek  for bug
