### ISSUE TITLE
HTML logs stored in local causes unnecessary sync traffic

### ISSUE THREAD

**Issue by m3rlinux** [simonmeggle/robotmk#191]
This is most likely caused by the fact that I have chosen the wrong place for the logs. Sorry.  :-|
Each time you save configuration on the master, it synchronizes the contents below of local/share .... to the slaves (as well as  installed MKPs, local checks etc.). 
The better place would be under var/. This would require to change the apache config as well as the robotmk check. But it would allow to safely rsync the data to the master. 
Would you open an issue for that please? 
Thanks, 
Simon

_Originally posted by @simonmeggle in https://github.com/simonmeggle/robotmk/issues/48#issuecomment-1034786897_

**Comment by simonmeggle** [comment]
The next CMK release will contain native support for Robotmk HTML log files.
No need to adopt the apache configuration anymore.

**Comment by simonmeggle** [comment]
Done with #201
