### ISSUE TITLE
Temporary disabling of robot suites

### ISSUE THREAD

**Issue by kleinski** [simonmeggle/robotmk#192]
Hello Simon,

here now as discussed my feature request: It would be useful to disable temporarily the execution and the result processing of certain robot suites using two mechanisms:
1. Placing a file named "DISABLED" into the root folder of a suite (with or without content, because it may contain a remark which describes the reason for the disabling) 
2. Using a regex pattern in the RobotMK agent plugin ruleset to determine the name of robot suites which shall be treated as disabled

And it would be good to have the possibility to set the service state of suites which are disabled via the RobotMK service monitoring rule.

Thanks in advance!

Marcus

**Comment by simonmeggle** [comment]
Thanks, this is a geat suggestion! I will take a closer look!

**Comment by simonmeggle** [comment]
> And it would be good to have the possibility to set the service state of suites which are disabled via the RobotMK service monitoring rule.

@kleinski Working on this - would it be sufficient to just skip the execution of DISABLED suites and let the services in CMK go stale?

**Comment by kleinski** [comment]
> @kleinski Working on this - would it be sufficient to just skip the execution of DISABLED suites and let the services in CMK go stale?

Yes, that would work out, I think. Main topic is to skip the executions, without any error state of the RobotMK services.

**Comment by simonmeggle** [comment]
This is implemented in 1.2.10-beta.1
