### ISSUE TITLE
Distribute test repository with bakery

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#27]
The bakery also should bake the test repository into the agent. 

Add global setting to WATO: 
```
[  ] Clone test repository with GIT from this location:
      [__________________________]
```
Requires git on the monitoring host and keybased passwordless access to the git server. 
Bakery clones the repo into `/usr/lib/check_mk_agent/robotmk`.

**Comment by mike1098** [comment]
Hello Simon, there is the rule "Distribute custom files" in the agent bakery which does the job already. I tested this with NT and POSIX system and it correct deliver the robot files to the right places where the agentplugin can handle it.
In case you want to use git you could integrate the directories for custom files in the checkmk site int the git repo. Anyway you need to bake a new agent and distribute it. Please let me know if you need help with this.

**Comment by simonmeggle** [comment]
Currently, there is no need to do that. Feel free to re-open this issue if you have demand on this feature.
