### ISSUE TITLE
Check in bakery script if paths are OS compliant 

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#28]
There is no possibility in the bakery rule to determine which OS the target system will be. 
For this reason, we are forced to check the path fields with a regex matching both windows and linux paths.

Adopt the bakery script so that it produces a meaningful error when the target OS during build time is e.g. windows but the path does not match windows regex. And vice versa.

**Comment by mike1098** [comment]
Hello Simon, This is not necessary. You can manage that with the conditions of the rule set. YOu just need then two rules, one for NT and one for POSIX systems.
IN our case we maintain a tag fr each OS, so this is easy, straight forward and follows the checkmk approach.

**Comment by simonmeggle** [comment]
It's clear that you'll need two rules, for win and linux. This issue is only to ensure that the path format fits to the OS the rule is applied onto. It's only a small change in the bakery script which will prevent the bakery to bake an agent containing a path which is not OS compliant. Just to catch an error as early as much. 
But I think the issue title was misleading. I have changed that.

**Comment by mike1098** [comment]
Pleaase note that I already use Path from pathlib in the agent plugin to ensure the right path syntax according to the OS flavor (NT or POSIX). See https://docs.python.org/3/library/pathlib.html for details.

**Comment by simonmeggle** [comment]
I checked this, pathlib is not included in OMD/Python2.7.

**Comment by mike1098** [comment]
Thats correct for checkmk 1.6, in 2.7 you can use os.path normcase or normpath instead.
In checkmk 1.7 we have python 3.
Nevertheless the agent plugin doesnt depend on checkmk version.
