### ISSUE TITLE
Add a Contributing guide

### ISSUE THREAD

**Issue by RichardLitt** [simonmeggle/robotmk#39]
There's quite a few examples online. This lives at Contribute.md, and will help show contributors how to get involved.

One thing that isn't clear to me: what kind of contributions do you want? Is there a path to maintainership?

**Comment by simonmeggle** [comment]
Example: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

**Comment by simonmeggle** [comment]
@all-contributors please add @RichardLitt for mentoring
